dataVariables: 
  150/200:
    - STACK_V
    - STACK_I
    - STACK_TEMP
    - AMB_TEMP
    - INTERNAL_BATT_V
    - INTERNAL_BATT_I
    - PRESS_SW_H
    - PRESS_SW_L
    - FAN_DUTY
    - TARGET_TEMP
    - SFD_1
    - OUTPUT_1_V
    - OUTPUT_1_I
    - SFD_2
    - CUT_IN_V
    - OVERCHARGE_V
    - OVERCHARGE_T
    - SLEEP_T
    - START_STOP_CYCLES
    - ACI
    - TARGET_V
    - DIPI_1
    - OUTPUT_2_V
    - DIPI_2
    - OLD_DATE
    - OLD_TIME
    - IGNORE_1
    - IGNORE_2
    - IGNORE_3
    - IGNORE_4
    - IGNORE_5
    - FIRMWARE
    - IGNORE_6
    - MAX_P_W
    - POWER_1_W
    - POWER_2_W
    - IGNORE_7
    - RUNTIME_SEC
    - IGNORE_8
    - IGNORE_9
    - IGNORE_10
    - DATE
    - TIME

  OLD:
    - STACK_V
    - STACK_I
    - STACK_TEMP
    - AMB_TEMP
    - INTERNAL_BATT_V
    - INTERNAL BATT_I
    - PRESS_SW_H
    - PRESS_SW_L
    - FAN_DUTY
    - TARGET_TEMP
    - SFD_1
    - OUTPUT_2_V
    - OUTPUT_1_I
    - SFD_2
    - CUT_IN_V
    - OVERCHARGE_V
    - OVERCHARGE_T
    - SLEEP_T
    - START_STOP_CYCLES
    - IGNORE_1
    - TARGET_V
    - IGNORE_2
    - OLD_DATE
    - OLD_TIME
    - IGNORE_3
    - IGNORE_4
    - MAX_P_W
    - IGNORE_5
    - RUNTIME_SEC
    - IGNORE_6
    - IGNORE_7
    - IGNORE_8
    - IGNORE_9
    - IGNORE_10
    - IGNORE_11

  VOLD:
    - STACK_V
    - STACK_I
    - STACK_TEMP
    - AMB_TEMP
    - INTERNAL_BATT_V
    - INTERNAL BATT_I
    - PRESS_SW_H
    - PRESS_SW_L
    - FAN_DUTY
    - TARGET_TEMP
    - SFD_1
    - OUTPUT_2_V
    - OUTPUT_1_I
    - SFD_2
    - CUT_IN_V
    - OVERCHARGE_V
    - OVERCHARGE_T
    - SLEEP_T
    - START_STOP_CYCLES
    - IGNORE_1
    - TARGET_V
    - IGNORE_2
    - IGNORE_3
    - IGNORE_4
    - OLD_DATE
    - OLD_TIME
    - IGNORE_5
additionalVariables:
  - OUTPUT_POWER
  - TIME_ELAPSED
port: /dev/ttyUSB0
buffer: buffer.txt
baudrate: 9600
test_directory: data_dir
recipients: 
  - maxjay2000@gmail.com
  - stewart.dow@boc.com
