dataVariables: 
  - STACK_V
  - STACK_I
  - STACK_TEMP
  - AMB_TEMP
  - INTERNAL_BATT_V
  - INTERNAL_BATT_I
  - PRESS_SW_H
  - PRESS_SW_L
  - FAN_DUTY
  - TARGET_TEMP
  - SFD_1
  - OUTPUT_1_V
  - OUTPUT_1_I
  - SFD_2
  - CUT_IN_V
  - OVERCHARGE_V
  - OVERCHARGE_I
  - SLEEP_T
  - START_STOP_CYCLES
  - ACI
  - TARGET_V
  - DIPI_1
  - OUTPUT_2_V
  - DIPI_2
  - OLD_DATE
  - OLD_TIME
  - IGNORE_1
  - IGNORE_2
  - IGNORE_3
  - IGNORE_4
  - IGNORE_5
  - FIRMWARE
  - IGNORE_6
  - MAX_P_W
  - POWER_1_W
  - POWER_2_W
  - IGNORE_7
  - RUNTIME_SEC
  - IGNORE_8
  - IGNORE_9
  - IGNORE_10
  - DATE
  - TIME
additionalVariables:
  - POWER
  - TIME_ELAPSED
port: /dev/ttyUSB0
buffer: buffer.txt
test_directory: test_dir
recipients: 
  - maxjay2000@gmail.com
  - stewart.dow@boc.com
emailusr: boc.hymera.sys@gmail.com
emailpwd: Tango1234

